### PR TITLE
Fix issue of bad suggestions when query matches start of existing word

### LINKED ISSUE #1: Suggestions include query when they shouldn't
If my query includes an inserted word _as a prefix_, it includes my query in the list of suggestions.

If my query _starts with the same letter_ as an inserted word, I get a strange suggestion that appears to be the merging of the query and the inserted word.

```js
const completion = createTrie();

completion.suggest("listening"); // should be [], got []
completion.insert("list");
completion.suggest("listening"); // should still be [], got ["listening"]
completion.suggest("lost"); // should still be [], got ["lostist"] (!!!)
```

### PR DESCRIPTION
**Pull request by indiesquidge**
The private function getNodePath had a subtle bug in that it would still
return a list of nodes even if that list did not have a one-to-one
mapping of nodes to letters in the query. This resulted in suggestions
being populated with words if the query had *at least* one letter prefix
that matched the word, whereas it should only match if the query has
*exactly* a prefix of a word (meaning that queries longer than existing
words should also return an empty suggestions list).

Fixes #1

### CODE REVIEW

File: createTrie.js [hunk 1]
```diff
@@ -99,12 +99,15 @@ function createTrie() {
 
   // private methods
   function getNodePath(query) {
-    let nodePath = [rootNode];
+    let nodePath = [];
```
Comment (indiesquidge) [inline createTrie.js:102]: I'm not sure why I ever included `rootNode` in the node path … AFAICT it doesn't prevent any bugs or help any existing functionality.
